server.port=8761

spring.application.name=eureka-server

# config-server config
# spring.config.import=configserver:http://localhost:8888/

# eureka server - unregistering eureka client
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
