# See http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html

server.port=8082
spring.application.name=RestClient
spring.profiles.active=client_test

spring.boot.base.url=http://localhost:8081/api/help

spring.thymeleaf.cache=false
spring.main.show-banner=false
logging.level.jdbc=OFF
logging.level.jdbc.sqltiming=DEBUG
logging.level.jdbc.resultsettable=DEBUG
