server:
    port: 8888

spring:
    application:
        name: config-server

# git config
    cloud:
        config:
            server:
                git:
                    uri: https://github.com/devarajuc0402/config-repository.git
                    default-label: main
                    clone-on-start: true
                    force-pull: true
                    basedir: C:/Users/Smile/Desktop/Java_21/Workspace_Microservices/basedir-config-server

# local location 'file:/C:/Users/Smile/AppData/Local/Temp/config-repo-6966596740135116761/'

management:
    endpoints:
        web:
            exposure:
                include: health,info
