server.port=8888

spring.application.name=config-server

# local folder config
spring.cloud.config.server.native.search-locations=file:///C:/Users/Smile/Desktop/Java_21/Workspace_Microservices/config-repository/
spring.cloud.config.server.git.default-label=master
spring.profiles.active=native

# git config
# spring.cloud.config.server.git.uri=https://github.com/devarajuc0402/config-repository.git
# spring.cloud.config.server.git.default-label=main

# spring.profiles.active=config-server

management.endpoints.web.exposure.include=health,info

# spring.cloud.config.server.git.clone-on-start=true
# spring.cloud.config.server.git.force-pull=true
